<?php
declare(strict_types=1);

/**
 * AdminClientCreateRequest
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * AdminClientCreateRequest Class Doc Comment
 *
 * @description クライアント登録リクエスト。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AdminClientCreateRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'AdminClientCreateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'clientName' => 'string',
        'description' => 'string',
        'clientType' => 'string',
        'redirectUris' => 'string[]',
        'allowedScopes' => 'string[]',
        'grantTypesSupported' => 'string[]',
        'tokenEndpointAuthMethod' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'clientName' => null,
        'description' => null,
        'clientType' => null,
        'redirectUris' => 'uri',
        'allowedScopes' => null,
        'grantTypesSupported' => null,
        'tokenEndpointAuthMethod' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'clientName' => false,
        'description' => false,
        'clientType' => false,
        'redirectUris' => false,
        'allowedScopes' => false,
        'grantTypesSupported' => false,
        'tokenEndpointAuthMethod' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'clientName' => 'client_name',
        'description' => 'description',
        'clientType' => 'client_type',
        'redirectUris' => 'redirect_uris',
        'allowedScopes' => 'allowed_scopes',
        'grantTypesSupported' => 'grant_types_supported',
        'tokenEndpointAuthMethod' => 'token_endpoint_auth_method'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'clientName' => 'setClientName',
        'description' => 'setDescription',
        'clientType' => 'setClientType',
        'redirectUris' => 'setRedirectUris',
        'allowedScopes' => 'setAllowedScopes',
        'grantTypesSupported' => 'setGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'setTokenEndpointAuthMethod'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'clientName' => 'getClientName',
        'description' => 'getDescription',
        'clientType' => 'getClientType',
        'redirectUris' => 'getRedirectUris',
        'allowedScopes' => 'getAllowedScopes',
        'grantTypesSupported' => 'getGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'getTokenEndpointAuthMethod'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];
    public const CLIENT_TYPE_CONFIDENTIAL = 'confidential';
    public const ALLOWED_SCOPES_OPENID = 'openid';
    public const ALLOWED_SCOPES_PROFILE = 'profile';
    public const ALLOWED_SCOPES_EMAIL = 'email';
    public const ALLOWED_SCOPES_OFFLINE_ACCESS = 'offline_access';
    public const GRANT_TYPES_SUPPORTED_AUTHORIZATION_CODE = 'authorization_code';
    public const GRANT_TYPES_SUPPORTED_REFRESH_TOKEN = 'refresh_token';
    public const TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC = 'client_secret_basic';
    public const TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST = 'client_secret_post';
    public const TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT = 'private_key_jwt';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getClientTypeAllowableValues()
    {
        return [
            self::CLIENT_TYPE_CONFIDENTIAL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAllowedScopesAllowableValues()
    {
        return [
            self::ALLOWED_SCOPES_OPENID,
            self::ALLOWED_SCOPES_PROFILE,
            self::ALLOWED_SCOPES_EMAIL,
            self::ALLOWED_SCOPES_OFFLINE_ACCESS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getGrantTypesSupportedAllowableValues()
    {
        return [
            self::GRANT_TYPES_SUPPORTED_AUTHORIZATION_CODE,
            self::GRANT_TYPES_SUPPORTED_REFRESH_TOKEN,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getTokenEndpointAuthMethodAllowableValues()
    {
        return [
            self::TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC,
            self::TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST,
            self::TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientName', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('clientType', $data ?? [], null);
        $this->setIfExists('redirectUris', $data ?? [], null);
        $this->setIfExists('allowedScopes', $data ?? [], null);
        $this->setIfExists('grantTypesSupported', $data ?? [], null);
        $this->setIfExists('tokenEndpointAuthMethod', $data ?? [], 'client_secret_basic');
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['clientName'] === null) {
            $invalidProperties[] = "'clientName' can't be null";
        }
        if ((mb_strlen($this->container['clientName']) > 255)) {
            $invalidProperties[] = "invalid value for 'clientName', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['clientName']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientName', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 1000)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 1000.";
        }

        if ($this->container['clientType'] === null) {
            $invalidProperties[] = "'clientType' can't be null";
        }
        $allowedValues = self::getClientTypeAllowableValues();
        if (!is_null($this->container['clientType']) && !in_array($this->container['clientType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'clientType', must be one of '%s'",
                $this->container['clientType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['redirectUris'] === null) {
            $invalidProperties[] = "'redirectUris' can't be null";
        }
        if ((count($this->container['redirectUris']) < 1)) {
            $invalidProperties[] = "invalid value for 'redirectUris', number of items must be greater than or equal to 1.";
        }

        if ($this->container['allowedScopes'] === null) {
            $invalidProperties[] = "'allowedScopes' can't be null";
        }
        if ((count($this->container['allowedScopes']) < 1)) {
            $invalidProperties[] = "invalid value for 'allowedScopes', number of items must be greater than or equal to 1.";
        }

        if ($this->container['grantTypesSupported'] === null) {
            $invalidProperties[] = "'grantTypesSupported' can't be null";
        }
        if ((count($this->container['grantTypesSupported']) < 1)) {
            $invalidProperties[] = "invalid value for 'grantTypesSupported', number of items must be greater than or equal to 1.";
        }

        $allowedValues = self::getTokenEndpointAuthMethodAllowableValues();
        if (!is_null($this->container['tokenEndpointAuthMethod']) && !in_array($this->container['tokenEndpointAuthMethod'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tokenEndpointAuthMethod', must be one of '%s'",
                $this->container['tokenEndpointAuthMethod'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientName
     *
     * @return string
     */
    public function getClientName(): string
    {
        return $this->container['clientName'];
    }

    /**
     * Sets clientName
     *
     * @param string $clientName クライアントアプリケーションの表示名。
     *
     * @return $this
     */
    public function setClientName(string $clientName): static
    {
        if (is_null($clientName)) {
            throw new InvalidArgumentException('non-nullable clientName cannot be null');
        }
        if ((mb_strlen($clientName) > 255)) {
            throw new InvalidArgumentException('invalid length for $clientName when calling AdminClientCreateRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($clientName) < 1)) {
            throw new InvalidArgumentException('invalid length for $clientName when calling AdminClientCreateRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientName'] = $clientName;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description クライアントの説明（オプション）。
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 1000)) {
            throw new InvalidArgumentException('invalid length for $description when calling AdminClientCreateRequest., must be smaller than or equal to 1000.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets clientType
     *
     * @return string
     */
    public function getClientType(): string
    {
        return $this->container['clientType'];
    }

    /**
     * Sets clientType
     *
     * @param string $clientType クライアントタイプ。  - `confidential`: 機密クライアント（サーバーサイドアプリ）
     *
     * @return $this
     */
    public function setClientType(string $clientType): static
    {
        if (is_null($clientType)) {
            throw new InvalidArgumentException('non-nullable clientType cannot be null');
        }
        $allowedValues = self::getClientTypeAllowableValues();
        if (!in_array($clientType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'clientType', must be one of '%s'",
                    $clientType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['clientType'] = $clientType;

        return $this;
    }

    /**
     * Gets redirectUris
     *
     * @return string[]
     */
    public function getRedirectUris(): array
    {
        return $this->container['redirectUris'];
    }

    /**
     * Sets redirectUris
     *
     * @param string[] $redirectUris 許可するリダイレクト URI のリスト。
     *
     * @return $this
     */
    public function setRedirectUris(array $redirectUris): static
    {
        if (is_null($redirectUris)) {
            throw new InvalidArgumentException('non-nullable redirectUris cannot be null');
        }


        if ((count($redirectUris) < 1)) {
            throw new InvalidArgumentException('invalid length for $redirectUris when calling AdminClientCreateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['redirectUris'] = $redirectUris;

        return $this;
    }

    /**
     * Gets allowedScopes
     *
     * @return string[]
     */
    public function getAllowedScopes(): array
    {
        return $this->container['allowedScopes'];
    }

    /**
     * Sets allowedScopes
     *
     * @param string[] $allowedScopes このクライアントに許可するスコープのリスト。
     *
     * @return $this
     */
    public function setAllowedScopes(array $allowedScopes): static
    {
        if (is_null($allowedScopes)) {
            throw new InvalidArgumentException('non-nullable allowedScopes cannot be null');
        }
        $allowedValues = self::getAllowedScopesAllowableValues();
        if (array_diff($allowedScopes, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'allowedScopes', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($allowedScopes) < 1)) {
            throw new InvalidArgumentException('invalid length for $allowedScopes when calling AdminClientCreateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['allowedScopes'] = $allowedScopes;

        return $this;
    }

    /**
     * Gets grantTypesSupported
     *
     * @return string[]
     */
    public function getGrantTypesSupported(): array
    {
        return $this->container['grantTypesSupported'];
    }

    /**
     * Sets grantTypesSupported
     *
     * @param string[] $grantTypesSupported このクライアントに許可するグラントタイプのリスト。
     *
     * @return $this
     */
    public function setGrantTypesSupported(array $grantTypesSupported): static
    {
        if (is_null($grantTypesSupported)) {
            throw new InvalidArgumentException('non-nullable grantTypesSupported cannot be null');
        }
        $allowedValues = self::getGrantTypesSupportedAllowableValues();
        if (array_diff($grantTypesSupported, $allowedValues)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value for 'grantTypesSupported', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }


        if ((count($grantTypesSupported) < 1)) {
            throw new InvalidArgumentException('invalid length for $grantTypesSupported when calling AdminClientCreateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['grantTypesSupported'] = $grantTypesSupported;

        return $this;
    }

    /**
     * Gets tokenEndpointAuthMethod
     *
     * @return string|null
     */
    public function getTokenEndpointAuthMethod(): ?string
    {
        return $this->container['tokenEndpointAuthMethod'];
    }

    /**
     * Sets tokenEndpointAuthMethod
     *
     * @param string|null $tokenEndpointAuthMethod トークンエンドポイントでのクライアント認証方式。  - `client_secret_basic`: HTTP Basic 認証（デフォルト） - `client_secret_post`: リクエストボディでの送信 - `private_key_jwt`: JWT による認証
     *
     * @return $this
     */
    public function setTokenEndpointAuthMethod(?string $tokenEndpointAuthMethod): static
    {
        if (is_null($tokenEndpointAuthMethod)) {
            throw new InvalidArgumentException('non-nullable tokenEndpointAuthMethod cannot be null');
        }
        $allowedValues = self::getTokenEndpointAuthMethodAllowableValues();
        if (!in_array($tokenEndpointAuthMethod, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tokenEndpointAuthMethod', must be one of '%s'",
                    $tokenEndpointAuthMethod,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tokenEndpointAuthMethod'] = $tokenEndpointAuthMethod;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


