<?php
declare(strict_types=1);

/**
 * AdminClientCreatedResponse
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;

/**
 * AdminClientCreatedResponse Class Doc Comment
 *
 * @description クライアント登録成功レスポンス。  **重要**: &#x60;client_secret&#x60; はこのレスポンスでのみ返却されます。 後から再取得することはできないため、安全な場所に保存してください。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AdminClientCreatedResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'AdminClientCreatedResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'clientId' => 'string',
        'clientSecret' => 'string',
        'clientName' => 'string',
        'description' => 'string',
        'clientType' => 'string',
        'redirectUris' => 'string[]',
        'allowedScopes' => 'string[]',
        'grantTypesSupported' => 'string[]',
        'tokenEndpointAuthMethod' => 'string',
        'isActive' => 'bool',
        'createdAt' => '\DateTime',
        'updatedAt' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'clientId' => null,
        'clientSecret' => null,
        'clientName' => null,
        'description' => null,
        'clientType' => null,
        'redirectUris' => 'uri',
        'allowedScopes' => null,
        'grantTypesSupported' => null,
        'tokenEndpointAuthMethod' => null,
        'isActive' => null,
        'createdAt' => 'date-time',
        'updatedAt' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'clientId' => false,
        'clientSecret' => false,
        'clientName' => false,
        'description' => true,
        'clientType' => false,
        'redirectUris' => false,
        'allowedScopes' => false,
        'grantTypesSupported' => false,
        'tokenEndpointAuthMethod' => false,
        'isActive' => false,
        'createdAt' => false,
        'updatedAt' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'clientId' => 'client_id',
        'clientSecret' => 'client_secret',
        'clientName' => 'client_name',
        'description' => 'description',
        'clientType' => 'client_type',
        'redirectUris' => 'redirect_uris',
        'allowedScopes' => 'allowed_scopes',
        'grantTypesSupported' => 'grant_types_supported',
        'tokenEndpointAuthMethod' => 'token_endpoint_auth_method',
        'isActive' => 'is_active',
        'createdAt' => 'created_at',
        'updatedAt' => 'updated_at'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'clientId' => 'setClientId',
        'clientSecret' => 'setClientSecret',
        'clientName' => 'setClientName',
        'description' => 'setDescription',
        'clientType' => 'setClientType',
        'redirectUris' => 'setRedirectUris',
        'allowedScopes' => 'setAllowedScopes',
        'grantTypesSupported' => 'setGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'setTokenEndpointAuthMethod',
        'isActive' => 'setIsActive',
        'createdAt' => 'setCreatedAt',
        'updatedAt' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'clientId' => 'getClientId',
        'clientSecret' => 'getClientSecret',
        'clientName' => 'getClientName',
        'description' => 'getDescription',
        'clientType' => 'getClientType',
        'redirectUris' => 'getRedirectUris',
        'allowedScopes' => 'getAllowedScopes',
        'grantTypesSupported' => 'getGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'getTokenEndpointAuthMethod',
        'isActive' => 'getIsActive',
        'createdAt' => 'getCreatedAt',
        'updatedAt' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];
    public const CLIENT_TYPE_CONFIDENTIAL = 'confidential';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getClientTypeAllowableValues()
    {
        return [
            self::CLIENT_TYPE_CONFIDENTIAL,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('clientSecret', $data ?? [], null);
        $this->setIfExists('clientName', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('clientType', $data ?? [], null);
        $this->setIfExists('redirectUris', $data ?? [], null);
        $this->setIfExists('allowedScopes', $data ?? [], null);
        $this->setIfExists('grantTypesSupported', $data ?? [], null);
        $this->setIfExists('tokenEndpointAuthMethod', $data ?? [], null);
        $this->setIfExists('isActive', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('updatedAt', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['clientId'] === null) {
            $invalidProperties[] = "'clientId' can't be null";
        }
        if ($this->container['clientSecret'] === null) {
            $invalidProperties[] = "'clientSecret' can't be null";
        }
        if ($this->container['clientName'] === null) {
            $invalidProperties[] = "'clientName' can't be null";
        }
        if ($this->container['clientType'] === null) {
            $invalidProperties[] = "'clientType' can't be null";
        }
        $allowedValues = self::getClientTypeAllowableValues();
        if (!is_null($this->container['clientType']) && !in_array($this->container['clientType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'clientType', must be one of '%s'",
                $this->container['clientType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['redirectUris'] === null) {
            $invalidProperties[] = "'redirectUris' can't be null";
        }
        if ($this->container['allowedScopes'] === null) {
            $invalidProperties[] = "'allowedScopes' can't be null";
        }
        if ($this->container['grantTypesSupported'] === null) {
            $invalidProperties[] = "'grantTypesSupported' can't be null";
        }
        if ($this->container['tokenEndpointAuthMethod'] === null) {
            $invalidProperties[] = "'tokenEndpointAuthMethod' can't be null";
        }
        if ($this->container['isActive'] === null) {
            $invalidProperties[] = "'isActive' can't be null";
        }
        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        if ($this->container['updatedAt'] === null) {
            $invalidProperties[] = "'updatedAt' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientId
     *
     * @return string
     */
    public function getClientId(): string
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string $clientId 発行されたクライアント識別子。
     *
     * @return $this
     */
    public function setClientId(string $clientId): static
    {
        if (is_null($clientId)) {
            throw new InvalidArgumentException('non-nullable clientId cannot be null');
        }
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets clientSecret
     *
     * @return string
     */
    public function getClientSecret(): string
    {
        return $this->container['clientSecret'];
    }

    /**
     * Sets clientSecret
     *
     * @param string $clientSecret 発行されたクライアントシークレット。  **重要**: この値は一度しか表示されません。安全な場所に保存してください。
     *
     * @return $this
     */
    public function setClientSecret(string $clientSecret): static
    {
        if (is_null($clientSecret)) {
            throw new InvalidArgumentException('non-nullable clientSecret cannot be null');
        }
        $this->container['clientSecret'] = $clientSecret;

        return $this;
    }

    /**
     * Gets clientName
     *
     * @return string
     */
    public function getClientName(): string
    {
        return $this->container['clientName'];
    }

    /**
     * Sets clientName
     *
     * @param string $clientName クライアントアプリケーションの表示名。
     *
     * @return $this
     */
    public function setClientName(string $clientName): static
    {
        if (is_null($clientName)) {
            throw new InvalidArgumentException('non-nullable clientName cannot be null');
        }
        $this->container['clientName'] = $clientName;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description クライアントの説明。
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets clientType
     *
     * @return string
     */
    public function getClientType(): string
    {
        return $this->container['clientType'];
    }

    /**
     * Sets clientType
     *
     * @param string $clientType クライアントタイプ。
     *
     * @return $this
     */
    public function setClientType(string $clientType): static
    {
        if (is_null($clientType)) {
            throw new InvalidArgumentException('non-nullable clientType cannot be null');
        }
        $allowedValues = self::getClientTypeAllowableValues();
        if (!in_array($clientType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'clientType', must be one of '%s'",
                    $clientType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['clientType'] = $clientType;

        return $this;
    }

    /**
     * Gets redirectUris
     *
     * @return string[]
     */
    public function getRedirectUris(): array
    {
        return $this->container['redirectUris'];
    }

    /**
     * Sets redirectUris
     *
     * @param string[] $redirectUris 許可されたリダイレクト URI のリスト。
     *
     * @return $this
     */
    public function setRedirectUris(array $redirectUris): static
    {
        if (is_null($redirectUris)) {
            throw new InvalidArgumentException('non-nullable redirectUris cannot be null');
        }
        $this->container['redirectUris'] = $redirectUris;

        return $this;
    }

    /**
     * Gets allowedScopes
     *
     * @return string[]
     */
    public function getAllowedScopes(): array
    {
        return $this->container['allowedScopes'];
    }

    /**
     * Sets allowedScopes
     *
     * @param string[] $allowedScopes このクライアントに許可されたスコープのリスト。
     *
     * @return $this
     */
    public function setAllowedScopes(array $allowedScopes): static
    {
        if (is_null($allowedScopes)) {
            throw new InvalidArgumentException('non-nullable allowedScopes cannot be null');
        }
        $this->container['allowedScopes'] = $allowedScopes;

        return $this;
    }

    /**
     * Gets grantTypesSupported
     *
     * @return string[]
     */
    public function getGrantTypesSupported(): array
    {
        return $this->container['grantTypesSupported'];
    }

    /**
     * Sets grantTypesSupported
     *
     * @param string[] $grantTypesSupported このクライアントに許可されたグラントタイプのリスト。
     *
     * @return $this
     */
    public function setGrantTypesSupported(array $grantTypesSupported): static
    {
        if (is_null($grantTypesSupported)) {
            throw new InvalidArgumentException('non-nullable grantTypesSupported cannot be null');
        }
        $this->container['grantTypesSupported'] = $grantTypesSupported;

        return $this;
    }

    /**
     * Gets tokenEndpointAuthMethod
     *
     * @return string
     */
    public function getTokenEndpointAuthMethod(): string
    {
        return $this->container['tokenEndpointAuthMethod'];
    }

    /**
     * Sets tokenEndpointAuthMethod
     *
     * @param string $tokenEndpointAuthMethod トークンエンドポイントでのクライアント認証方式。
     *
     * @return $this
     */
    public function setTokenEndpointAuthMethod(string $tokenEndpointAuthMethod): static
    {
        if (is_null($tokenEndpointAuthMethod)) {
            throw new InvalidArgumentException('non-nullable tokenEndpointAuthMethod cannot be null');
        }
        $this->container['tokenEndpointAuthMethod'] = $tokenEndpointAuthMethod;

        return $this;
    }

    /**
     * Gets isActive
     *
     * @return bool
     */
    public function getIsActive(): bool
    {
        return $this->container['isActive'];
    }

    /**
     * Sets isActive
     *
     * @param bool $isActive クライアントが有効かどうか。
     *
     * @return $this
     */
    public function setIsActive(bool $isActive): static
    {
        if (is_null($isActive)) {
            throw new InvalidArgumentException('non-nullable isActive cannot be null');
        }
        $this->container['isActive'] = $isActive;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt クライアント登録日時（ISO 8601 形式）。
     *
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt): static
    {
        if (is_null($createdAt)) {
            throw new InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets updatedAt
     *
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->container['updatedAt'];
    }

    /**
     * Sets updatedAt
     *
     * @param \DateTime $updatedAt クライアント最終更新日時（ISO 8601 形式）。
     *
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt): static
    {
        if (is_null($updatedAt)) {
            throw new InvalidArgumentException('non-nullable updatedAt cannot be null');
        }
        $this->container['updatedAt'] = $updatedAt;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


