<?php
declare(strict_types=1);

/**
 * AdminClientUpdateRequest
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.6.1
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * AdminClientUpdateRequest Class Doc Comment
 *
 * @description クライアント更新リクエスト。 指定されたフィールドのみが更新されます。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class AdminClientUpdateRequest implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'AdminClientUpdateRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'clientName' => 'string',
        'description' => 'string',
        'redirectUris' => 'string[]',
        'postLogoutRedirectUris' => 'string[]',
        'allowedScopes' => '\Studio\Auth\Model\ScopeValue[]',
        'grantTypesSupported' => '\Studio\Auth\Model\GrantType[]',
        'tokenEndpointAuthMethod' => '\Studio\Auth\Model\TokenEndpointAuthMethod',
        'isActive' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'clientName' => null,
        'description' => null,
        'redirectUris' => 'uri',
        'postLogoutRedirectUris' => 'uri',
        'allowedScopes' => null,
        'grantTypesSupported' => null,
        'tokenEndpointAuthMethod' => null,
        'isActive' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'clientName' => false,
        'description' => true,
        'redirectUris' => false,
        'postLogoutRedirectUris' => false,
        'allowedScopes' => false,
        'grantTypesSupported' => false,
        'tokenEndpointAuthMethod' => false,
        'isActive' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'clientName' => 'client_name',
        'description' => 'description',
        'redirectUris' => 'redirect_uris',
        'postLogoutRedirectUris' => 'post_logout_redirect_uris',
        'allowedScopes' => 'allowed_scopes',
        'grantTypesSupported' => 'grant_types_supported',
        'tokenEndpointAuthMethod' => 'token_endpoint_auth_method',
        'isActive' => 'is_active'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'clientName' => 'setClientName',
        'description' => 'setDescription',
        'redirectUris' => 'setRedirectUris',
        'postLogoutRedirectUris' => 'setPostLogoutRedirectUris',
        'allowedScopes' => 'setAllowedScopes',
        'grantTypesSupported' => 'setGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'setTokenEndpointAuthMethod',
        'isActive' => 'setIsActive'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'clientName' => 'getClientName',
        'description' => 'getDescription',
        'redirectUris' => 'getRedirectUris',
        'postLogoutRedirectUris' => 'getPostLogoutRedirectUris',
        'allowedScopes' => 'getAllowedScopes',
        'grantTypesSupported' => 'getGrantTypesSupported',
        'tokenEndpointAuthMethod' => 'getTokenEndpointAuthMethod',
        'isActive' => 'getIsActive'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('clientName', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('redirectUris', $data ?? [], null);
        $this->setIfExists('postLogoutRedirectUris', $data ?? [], null);
        $this->setIfExists('allowedScopes', $data ?? [], null);
        $this->setIfExists('grantTypesSupported', $data ?? [], null);
        $this->setIfExists('tokenEndpointAuthMethod', $data ?? [], null);
        $this->setIfExists('isActive', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if (!is_null($this->container['clientName']) && (mb_strlen($this->container['clientName']) > 255)) {
            $invalidProperties[] = "invalid value for 'clientName', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['clientName']) && (mb_strlen($this->container['clientName']) < 1)) {
            $invalidProperties[] = "invalid value for 'clientName', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 1000)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 1000.";
        }

        if (!is_null($this->container['redirectUris']) && (count($this->container['redirectUris']) < 1)) {
            $invalidProperties[] = "invalid value for 'redirectUris', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['allowedScopes']) && (count($this->container['allowedScopes']) < 1)) {
            $invalidProperties[] = "invalid value for 'allowedScopes', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['grantTypesSupported']) && (count($this->container['grantTypesSupported']) < 1)) {
            $invalidProperties[] = "invalid value for 'grantTypesSupported', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets clientName
     *
     * @return string|null
     */
    public function getClientName(): ?string
    {
        return $this->container['clientName'];
    }

    /**
     * Sets clientName
     *
     * @param string|null $clientName クライアントアプリケーションの表示名。
     *
     * @return $this
     */
    public function setClientName(?string $clientName): static
    {
        if (is_null($clientName)) {
            throw new InvalidArgumentException('non-nullable clientName cannot be null');
        }
        if ((mb_strlen($clientName) > 255)) {
            throw new InvalidArgumentException('invalid length for $clientName when calling AdminClientUpdateRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($clientName) < 1)) {
            throw new InvalidArgumentException('invalid length for $clientName when calling AdminClientUpdateRequest., must be bigger than or equal to 1.');
        }

        $this->container['clientName'] = $clientName;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description クライアントの説明。`null` を指定すると説明を削除します。
     *
     * @return $this
     */
    public function setDescription(?string $description): static
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($description) && (mb_strlen($description) > 1000)) {
            throw new InvalidArgumentException('invalid length for $description when calling AdminClientUpdateRequest., must be smaller than or equal to 1000.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets redirectUris
     *
     * @return string[]|null
     */
    public function getRedirectUris(): ?array
    {
        return $this->container['redirectUris'];
    }

    /**
     * Sets redirectUris
     *
     * @param string[]|null $redirectUris 許可するリダイレクト URI のリスト。
     *
     * @return $this
     */
    public function setRedirectUris(?array $redirectUris): static
    {
        if (is_null($redirectUris)) {
            throw new InvalidArgumentException('non-nullable redirectUris cannot be null');
        }


        if ((count($redirectUris) < 1)) {
            throw new InvalidArgumentException('invalid length for $redirectUris when calling AdminClientUpdateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['redirectUris'] = $redirectUris;

        return $this;
    }

    /**
     * Gets postLogoutRedirectUris
     *
     * @return string[]|null
     */
    public function getPostLogoutRedirectUris(): ?array
    {
        return $this->container['postLogoutRedirectUris'];
    }

    /**
     * Sets postLogoutRedirectUris
     *
     * @param string[]|null $postLogoutRedirectUris RP-initiated logout（OIDC）でログアウト後に戻す URI のリスト。 指定した場合は既存の登録をこの内容で置き換えます。空配列を指定するとすべて削除します。
     *
     * @return $this
     */
    public function setPostLogoutRedirectUris(?array $postLogoutRedirectUris): static
    {
        if (is_null($postLogoutRedirectUris)) {
            throw new InvalidArgumentException('non-nullable postLogoutRedirectUris cannot be null');
        }
        $this->container['postLogoutRedirectUris'] = $postLogoutRedirectUris;

        return $this;
    }

    /**
     * Gets allowedScopes
     *
     * @return \Studio\Auth\Model\ScopeValue[]|null
     */
    public function getAllowedScopes(): ?array
    {
        return $this->container['allowedScopes'];
    }

    /**
     * Sets allowedScopes
     *
     * @param \Studio\Auth\Model\ScopeValue[]|null $allowedScopes このクライアントに許可するスコープのリスト。
     *
     * @return $this
     */
    public function setAllowedScopes(?array $allowedScopes): static
    {
        if (is_null($allowedScopes)) {
            throw new InvalidArgumentException('non-nullable allowedScopes cannot be null');
        }


        if ((count($allowedScopes) < 1)) {
            throw new InvalidArgumentException('invalid length for $allowedScopes when calling AdminClientUpdateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['allowedScopes'] = $allowedScopes;

        return $this;
    }

    /**
     * Gets grantTypesSupported
     *
     * @return \Studio\Auth\Model\GrantType[]|null
     */
    public function getGrantTypesSupported(): ?array
    {
        return $this->container['grantTypesSupported'];
    }

    /**
     * Sets grantTypesSupported
     *
     * @param \Studio\Auth\Model\GrantType[]|null $grantTypesSupported このクライアントに許可するグラントタイプのリスト。
     *
     * @return $this
     */
    public function setGrantTypesSupported(?array $grantTypesSupported): static
    {
        if (is_null($grantTypesSupported)) {
            throw new InvalidArgumentException('non-nullable grantTypesSupported cannot be null');
        }


        if ((count($grantTypesSupported) < 1)) {
            throw new InvalidArgumentException('invalid length for $grantTypesSupported when calling AdminClientUpdateRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['grantTypesSupported'] = $grantTypesSupported;

        return $this;
    }

    /**
     * Gets tokenEndpointAuthMethod
     *
     * @return \Studio\Auth\Model\TokenEndpointAuthMethod|null
     */
    public function getTokenEndpointAuthMethod(): ?\Studio\Auth\Model\TokenEndpointAuthMethod
    {
        return $this->container['tokenEndpointAuthMethod'];
    }

    /**
     * Sets tokenEndpointAuthMethod
     *
     * @param \Studio\Auth\Model\TokenEndpointAuthMethod|null $tokenEndpointAuthMethod tokenEndpointAuthMethod
     *
     * @return $this
     */
    public function setTokenEndpointAuthMethod(?\Studio\Auth\Model\TokenEndpointAuthMethod $tokenEndpointAuthMethod): static
    {
        if (is_null($tokenEndpointAuthMethod)) {
            throw new InvalidArgumentException('non-nullable tokenEndpointAuthMethod cannot be null');
        }
        $this->container['tokenEndpointAuthMethod'] = $tokenEndpointAuthMethod;

        return $this;
    }

    /**
     * Gets isActive
     *
     * @return bool|null
     */
    public function getIsActive(): ?bool
    {
        return $this->container['isActive'];
    }

    /**
     * Sets isActive
     *
     * @param bool|null $isActive クライアントの有効/無効を切り替えます。
     *
     * @return $this
     */
    public function setIsActive(?bool $isActive): static
    {
        if (is_null($isActive)) {
            throw new InvalidArgumentException('non-nullable isActive cannot be null');
        }
        $this->container['isActive'] = $isActive;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


