<?php
declare(strict_types=1);

/**
 * ClientType
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.5.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * ClientType Class Doc Comment
 *
 * @description クライアントタイプ。  - &#x60;confidential&#x60;: 機密クライアント（サーバーサイドアプリ）。クライアントシークレットを安全に保持可能。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ClientType: string
{
    case CONFIDENTIAL = 'confidential';
}


