<?php
declare(strict_types=1);

/**
 * EcJsonWebKey
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;

/**
 * EcJsonWebKey Class Doc Comment
 *
 * @description EC JSON Web Key (JWK)。 楕円曲線 (Elliptic Curve) 公開鍵を JSON 形式で表現します (RFC 7517)。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class EcJsonWebKey implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'EcJsonWebKey';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'kty' => 'string',
        'use' => 'string',
        'kid' => 'string',
        'alg' => 'string',
        'crv' => 'string',
        'x' => 'string',
        'y' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'kty' => null,
        'use' => null,
        'kid' => null,
        'alg' => null,
        'crv' => null,
        'x' => null,
        'y' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'kty' => false,
        'use' => false,
        'kid' => false,
        'alg' => false,
        'crv' => false,
        'x' => false,
        'y' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'kty' => 'kty',
        'use' => 'use',
        'kid' => 'kid',
        'alg' => 'alg',
        'crv' => 'crv',
        'x' => 'x',
        'y' => 'y'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'kty' => 'setKty',
        'use' => 'setUse',
        'kid' => 'setKid',
        'alg' => 'setAlg',
        'crv' => 'setCrv',
        'x' => 'setX',
        'y' => 'setY'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'kty' => 'getKty',
        'use' => 'getUse',
        'kid' => 'getKid',
        'alg' => 'getAlg',
        'crv' => 'getCrv',
        'x' => 'getX',
        'y' => 'getY'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const KTY_EC = 'EC';
    public const MODEL_USE_SIG = 'sig';
    public const ALG_ES256 = 'ES256';
    public const CRV_P_256 = 'P-256';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getKtyAllowableValues()
    {
        return [
            self::KTY_EC,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getUseAllowableValues()
    {
        return [
            self::MODEL_USE_SIG,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getAlgAllowableValues()
    {
        return [
            self::ALG_ES256,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getCrvAllowableValues()
    {
        return [
            self::CRV_P_256,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('kty', $data ?? [], null);
        $this->setIfExists('use', $data ?? [], null);
        $this->setIfExists('kid', $data ?? [], null);
        $this->setIfExists('alg', $data ?? [], null);
        $this->setIfExists('crv', $data ?? [], null);
        $this->setIfExists('x', $data ?? [], null);
        $this->setIfExists('y', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['kty'] === null) {
            $invalidProperties[] = "'kty' can't be null";
        }
        $allowedValues = self::getKtyAllowableValues();
        if (!is_null($this->container['kty']) && !in_array($this->container['kty'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'kty', must be one of '%s'",
                $this->container['kty'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['use'] === null) {
            $invalidProperties[] = "'use' can't be null";
        }
        $allowedValues = self::getUseAllowableValues();
        if (!is_null($this->container['use']) && !in_array($this->container['use'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'use', must be one of '%s'",
                $this->container['use'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['kid'] === null) {
            $invalidProperties[] = "'kid' can't be null";
        }
        if ($this->container['alg'] === null) {
            $invalidProperties[] = "'alg' can't be null";
        }
        $allowedValues = self::getAlgAllowableValues();
        if (!is_null($this->container['alg']) && !in_array($this->container['alg'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'alg', must be one of '%s'",
                $this->container['alg'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['crv'] === null) {
            $invalidProperties[] = "'crv' can't be null";
        }
        $allowedValues = self::getCrvAllowableValues();
        if (!is_null($this->container['crv']) && !in_array($this->container['crv'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'crv', must be one of '%s'",
                $this->container['crv'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['x'] === null) {
            $invalidProperties[] = "'x' can't be null";
        }
        if ($this->container['y'] === null) {
            $invalidProperties[] = "'y' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets kty
     *
     * @return string
     */
    public function getKty(): string
    {
        return $this->container['kty'];
    }

    /**
     * Sets kty
     *
     * @param string $kty 鍵タイプ (Key Type)。 EC 鍵の場合は \"EC\"。
     *
     * @return $this
     */
    public function setKty(string $kty): static
    {
        if (is_null($kty)) {
            throw new InvalidArgumentException('non-nullable kty cannot be null');
        }
        $allowedValues = self::getKtyAllowableValues();
        if (!in_array($kty, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'kty', must be one of '%s'",
                    $kty,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['kty'] = $kty;

        return $this;
    }

    /**
     * Gets use
     *
     * @return string
     */
    public function getUse(): string
    {
        return $this->container['use'];
    }

    /**
     * Sets use
     *
     * @param string $use 公開鍵の用途 (Public Key Use)。 署名検証用の場合は \"sig\"。
     *
     * @return $this
     */
    public function setUse(string $use): static
    {
        if (is_null($use)) {
            throw new InvalidArgumentException('non-nullable use cannot be null');
        }
        $allowedValues = self::getUseAllowableValues();
        if (!in_array($use, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'use', must be one of '%s'",
                    $use,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['use'] = $use;

        return $this;
    }

    /**
     * Gets kid
     *
     * @return string
     */
    public function getKid(): string
    {
        return $this->container['kid'];
    }

    /**
     * Sets kid
     *
     * @param string $kid 鍵 ID (Key ID)。 JWT ヘッダーの kid と照合して使用する鍵を特定します。
     *
     * @return $this
     */
    public function setKid(string $kid): static
    {
        if (is_null($kid)) {
            throw new InvalidArgumentException('non-nullable kid cannot be null');
        }
        $this->container['kid'] = $kid;

        return $this;
    }

    /**
     * Gets alg
     *
     * @return string
     */
    public function getAlg(): string
    {
        return $this->container['alg'];
    }

    /**
     * Sets alg
     *
     * @param string $alg アルゴリズム (Algorithm)。 この鍵で使用するアルゴリズムを示します。
     *
     * @return $this
     */
    public function setAlg(string $alg): static
    {
        if (is_null($alg)) {
            throw new InvalidArgumentException('non-nullable alg cannot be null');
        }
        $allowedValues = self::getAlgAllowableValues();
        if (!in_array($alg, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'alg', must be one of '%s'",
                    $alg,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['alg'] = $alg;

        return $this;
    }

    /**
     * Gets crv
     *
     * @return string
     */
    public function getCrv(): string
    {
        return $this->container['crv'];
    }

    /**
     * Sets crv
     *
     * @param string $crv 楕円曲線名 (Curve)。 ES256 の場合は \"P-256\"。
     *
     * @return $this
     */
    public function setCrv(string $crv): static
    {
        if (is_null($crv)) {
            throw new InvalidArgumentException('non-nullable crv cannot be null');
        }
        $allowedValues = self::getCrvAllowableValues();
        if (!in_array($crv, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'crv', must be one of '%s'",
                    $crv,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['crv'] = $crv;

        return $this;
    }

    /**
     * Gets x
     *
     * @return string
     */
    public function getX(): string
    {
        return $this->container['x'];
    }

    /**
     * Sets x
     *
     * @param string $x 楕円曲線の x 座標 (X Coordinate)。 Base64url エンコードされた値。
     *
     * @return $this
     */
    public function setX(string $x): static
    {
        if (is_null($x)) {
            throw new InvalidArgumentException('non-nullable x cannot be null');
        }
        $this->container['x'] = $x;

        return $this;
    }

    /**
     * Gets y
     *
     * @return string
     */
    public function getY(): string
    {
        return $this->container['y'];
    }

    /**
     * Sets y
     *
     * @param string $y 楕円曲線の y 座標 (Y Coordinate)。 Base64url エンコードされた値。
     *
     * @return $this
     */
    public function setY(string $y): static
    {
        if (is_null($y)) {
            throw new InvalidArgumentException('non-nullable y cannot be null');
        }
        $this->container['y'] = $y;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


