<?php
declare(strict_types=1);

/**
 * GrantType
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.4.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * GrantType Class Doc Comment
 *
 * @description OAuth 2.0 グラントタイプ (RFC 6749) および拡張グラント (RFC 6749 Section 4.5)。  - &#x60;authorization_code&#x60;: Authorization Code グラント (RFC 6749 Section 4.1)。&#x60;/oauth/authorize&#x60; で発行された認可コードをアクセストークンに交換します。 - &#x60;refresh_token&#x60;: Refresh Token グラント (RFC 6749 Section 6)。有効期限切れのアクセストークンを再発行します。 - &#x60;https://auth.studio.design/oauth/grant-types/pending-authentication-token&#x60;: Pending Authentication Token グラント (multi-organization picker 用)。&#x60;/oauth/authorize&#x60; が &#x60;organization_selection_required&#x60; エラーとともに発行した &#x60;pending_authentication_token&#x60; を、ユーザーが選択した &#x60;organization_id&#x60; と組み合わせて交換し、組織にバインドされたトークンを取得します。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum GrantType: string
{
    case AUTHORIZATION_CODE = 'authorization_code';

    case REFRESH_TOKEN = 'refresh_token';

    case PENDING_AUTHENTICATION_TOKEN = 'https://auth.studio.design/oauth/grant-types/pending-authentication-token';
}


