<?php
declare(strict_types=1);

/**
 * IntrospectResponse
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * IntrospectResponse Class Doc Comment
 *
 * @description RFC 7662 OAuth 2.0 Token Introspection に準拠したトークンイントロスペクションレスポンス。  &#x60;active&#x60; フィールドは常に含まれ、トークンが有効かどうかを示します。 トークンが有効な場合（&#x60;active: true&#x60;）、追加のメタ情報（スコープ、有効期限等）が含まれます。 トークンが無効な場合（&#x60;active: false&#x60;）、通常は &#x60;active&#x60; フィールドのみが返されます。  認可サーバーは、トークンの種類やリソースサーバーに応じて、 返却する情報を制限する場合があります。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class IntrospectResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'IntrospectResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'active' => 'bool',
        'scope' => 'string',
        'clientId' => 'string',
        'username' => 'string',
        'tokenType' => '\Studio\Auth\Model\TokenType',
        'exp' => 'int',
        'iat' => 'int',
        'nbf' => 'int',
        'sub' => 'string',
        'aud' => '\Studio\Auth\Model\IntrospectResponseAud',
        'iss' => 'string',
        'jti' => 'string',
        'email' => 'string',
        'emailVerified' => 'bool',
        'orgId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'active' => null,
        'scope' => null,
        'clientId' => null,
        'username' => null,
        'tokenType' => null,
        'exp' => 'int64',
        'iat' => 'int64',
        'nbf' => 'int64',
        'sub' => null,
        'aud' => null,
        'iss' => null,
        'jti' => null,
        'email' => 'email',
        'emailVerified' => null,
        'orgId' => 'uuid'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'active' => false,
        'scope' => false,
        'clientId' => false,
        'username' => false,
        'tokenType' => false,
        'exp' => false,
        'iat' => false,
        'nbf' => false,
        'sub' => false,
        'aud' => false,
        'iss' => false,
        'jti' => false,
        'email' => false,
        'emailVerified' => false,
        'orgId' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'active' => 'active',
        'scope' => 'scope',
        'clientId' => 'client_id',
        'username' => 'username',
        'tokenType' => 'token_type',
        'exp' => 'exp',
        'iat' => 'iat',
        'nbf' => 'nbf',
        'sub' => 'sub',
        'aud' => 'aud',
        'iss' => 'iss',
        'jti' => 'jti',
        'email' => 'email',
        'emailVerified' => 'email_verified',
        'orgId' => 'org_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'active' => 'setActive',
        'scope' => 'setScope',
        'clientId' => 'setClientId',
        'username' => 'setUsername',
        'tokenType' => 'setTokenType',
        'exp' => 'setExp',
        'iat' => 'setIat',
        'nbf' => 'setNbf',
        'sub' => 'setSub',
        'aud' => 'setAud',
        'iss' => 'setIss',
        'jti' => 'setJti',
        'email' => 'setEmail',
        'emailVerified' => 'setEmailVerified',
        'orgId' => 'setOrgId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'active' => 'getActive',
        'scope' => 'getScope',
        'clientId' => 'getClientId',
        'username' => 'getUsername',
        'tokenType' => 'getTokenType',
        'exp' => 'getExp',
        'iat' => 'getIat',
        'nbf' => 'getNbf',
        'sub' => 'getSub',
        'aud' => 'getAud',
        'iss' => 'getIss',
        'jti' => 'getJti',
        'email' => 'getEmail',
        'emailVerified' => 'getEmailVerified',
        'orgId' => 'getOrgId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('active', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('tokenType', $data ?? [], null);
        $this->setIfExists('exp', $data ?? [], null);
        $this->setIfExists('iat', $data ?? [], null);
        $this->setIfExists('nbf', $data ?? [], null);
        $this->setIfExists('sub', $data ?? [], null);
        $this->setIfExists('aud', $data ?? [], null);
        $this->setIfExists('iss', $data ?? [], null);
        $this->setIfExists('jti', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('emailVerified', $data ?? [], null);
        $this->setIfExists('orgId', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['active'] === null) {
            $invalidProperties[] = "'active' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active
     *
     * @return bool
     */
    public function getActive(): bool
    {
        return $this->container['active'];
    }

    /**
     * Sets active
     *
     * @param bool $active トークンが現在アクティブ（有効）かどうかを示すブール値。  `true` の場合、トークンは有効であり、追加のメタ情報が含まれます。 `false` の場合、トークンは無効（期限切れ、失効済み、不正等）です。
     *
     * @return $this
     */
    public function setActive(bool $active): static
    {
        if (is_null($active)) {
            throw new InvalidArgumentException('non-nullable active cannot be null');
        }
        $this->container['active'] = $active;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope(): ?string
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope トークンに関連付けられたスコープのスペース区切りリスト。 認可サーバーは、リソースサーバーに応じて返却するスコープを制限する場合があります。
     *
     * @return $this
     */
    public function setScope(?string $scope): static
    {
        if (is_null($scope)) {
            throw new InvalidArgumentException('non-nullable scope cannot be null');
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets clientId
     *
     * @return string|null
     */
    public function getClientId(): ?string
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string|null $clientId トークンを要求したクライアントの識別子。
     *
     * @return $this
     */
    public function setClientId(?string $clientId): static
    {
        if (is_null($clientId)) {
            throw new InvalidArgumentException('non-nullable clientId cannot be null');
        }
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername(): ?string
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username トークンに関連付けられたリソースオーナーの人間が読める識別子。
     *
     * @return $this
     */
    public function setUsername(?string $username): static
    {
        if (is_null($username)) {
            throw new InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets tokenType
     *
     * @return \Studio\Auth\Model\TokenType|null
     */
    public function getTokenType(): ?\Studio\Auth\Model\TokenType
    {
        return $this->container['tokenType'];
    }

    /**
     * Sets tokenType
     *
     * @param \Studio\Auth\Model\TokenType|null $tokenType tokenType
     *
     * @return $this
     */
    public function setTokenType(?\Studio\Auth\Model\TokenType $tokenType): static
    {
        if (is_null($tokenType)) {
            throw new InvalidArgumentException('non-nullable tokenType cannot be null');
        }
        $this->container['tokenType'] = $tokenType;

        return $this;
    }

    /**
     * Gets exp
     *
     * @return int|null
     */
    public function getExp(): ?int
    {
        return $this->container['exp'];
    }

    /**
     * Sets exp
     *
     * @param int|null $exp トークンの有効期限を示す UNIX タイムスタンプ（秒）。 RFC 7519 Section 4.1.4 で定義されています。
     *
     * @return $this
     */
    public function setExp(?int $exp): static
    {
        if (is_null($exp)) {
            throw new InvalidArgumentException('non-nullable exp cannot be null');
        }
        $this->container['exp'] = $exp;

        return $this;
    }

    /**
     * Gets iat
     *
     * @return int|null
     */
    public function getIat(): ?int
    {
        return $this->container['iat'];
    }

    /**
     * Sets iat
     *
     * @param int|null $iat トークンが発行された時刻を示す UNIX タイムスタンプ（秒）。 RFC 7519 Section 4.1.6 で定義されています。
     *
     * @return $this
     */
    public function setIat(?int $iat): static
    {
        if (is_null($iat)) {
            throw new InvalidArgumentException('non-nullable iat cannot be null');
        }
        $this->container['iat'] = $iat;

        return $this;
    }

    /**
     * Gets nbf
     *
     * @return int|null
     */
    public function getNbf(): ?int
    {
        return $this->container['nbf'];
    }

    /**
     * Sets nbf
     *
     * @param int|null $nbf トークンが有効になる時刻（この時刻より前は無効）を示す UNIX タイムスタンプ（秒）。 RFC 7519 Section 4.1.5 で定義されています。
     *
     * @return $this
     */
    public function setNbf(?int $nbf): static
    {
        if (is_null($nbf)) {
            throw new InvalidArgumentException('non-nullable nbf cannot be null');
        }
        $this->container['nbf'] = $nbf;

        return $this;
    }

    /**
     * Gets sub
     *
     * @return string|null
     */
    public function getSub(): ?string
    {
        return $this->container['sub'];
    }

    /**
     * Sets sub
     *
     * @param string|null $sub トークンのサブジェクト（主体）を識別する一意の識別子。 通常はリソースオーナー（ユーザー）の識別子です。 RFC 7519 Section 4.1.2 で定義されています。
     *
     * @return $this
     */
    public function setSub(?string $sub): static
    {
        if (is_null($sub)) {
            throw new InvalidArgumentException('non-nullable sub cannot be null');
        }
        $this->container['sub'] = $sub;

        return $this;
    }

    /**
     * Gets aud
     *
     * @return \Studio\Auth\Model\IntrospectResponseAud|null
     */
    public function getAud(): ?\Studio\Auth\Model\IntrospectResponseAud
    {
        return $this->container['aud'];
    }

    /**
     * Sets aud
     *
     * @param \Studio\Auth\Model\IntrospectResponseAud|null $aud aud
     *
     * @return $this
     */
    public function setAud(?\Studio\Auth\Model\IntrospectResponseAud $aud): static
    {
        if (is_null($aud)) {
            throw new InvalidArgumentException('non-nullable aud cannot be null');
        }
        $this->container['aud'] = $aud;

        return $this;
    }

    /**
     * Gets iss
     *
     * @return string|null
     */
    public function getIss(): ?string
    {
        return $this->container['iss'];
    }

    /**
     * Sets iss
     *
     * @param string|null $iss トークンを発行した認可サーバーの識別子（URL）。 RFC 7519 Section 4.1.1 で定義されています。
     *
     * @return $this
     */
    public function setIss(?string $iss): static
    {
        if (is_null($iss)) {
            throw new InvalidArgumentException('non-nullable iss cannot be null');
        }
        $this->container['iss'] = $iss;

        return $this;
    }

    /**
     * Gets jti
     *
     * @return string|null
     */
    public function getJti(): ?string
    {
        return $this->container['jti'];
    }

    /**
     * Sets jti
     *
     * @param string|null $jti トークンの一意識別子（JWT ID）。 RFC 7519 Section 4.1.7 で定義されています。
     *
     * @return $this
     */
    public function setJti(?string $jti): static
    {
        if (is_null($jti)) {
            throw new InvalidArgumentException('non-nullable jti cannot be null');
        }
        $this->container['jti'] = $jti;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email トークンに関連付けられたユーザーのメールアドレス。 \"email\" スコープがトークンのスコープに含まれる場合のみ返されます。
     *
     * @return $this
     */
    public function setEmail(?string $email): static
    {
        if (is_null($email)) {
            throw new InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets emailVerified
     *
     * @return bool|null
     */
    public function getEmailVerified(): ?bool
    {
        return $this->container['emailVerified'];
    }

    /**
     * Sets emailVerified
     *
     * @param bool|null $emailVerified ユーザーのメールアドレスが検証済みかどうかを示すブール値。 \"email\" スコープがトークンのスコープに含まれる場合のみ返されます。
     *
     * @return $this
     */
    public function setEmailVerified(?bool $emailVerified): static
    {
        if (is_null($emailVerified)) {
            throw new InvalidArgumentException('non-nullable emailVerified cannot be null');
        }
        $this->container['emailVerified'] = $emailVerified;

        return $this;
    }

    /**
     * Gets orgId
     *
     * @return string|null
     */
    public function getOrgId(): ?string
    {
        return $this->container['orgId'];
    }

    /**
     * Sets orgId
     *
     * @param string|null $orgId トークンに紐づく組織識別子（UUID形式）。 アクセストークンに `org_id` クレームが含まれている場合に返却されます。 組織コンテキストを持たないトークンの場合は `null` または不在となります。
     *
     * @return $this
     */
    public function setOrgId(?string $orgId): static
    {
        if (is_null($orgId)) {
            array_push($this->openAPINullablesSetToNull, 'orgId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('orgId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['orgId'] = $orgId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


