<?php
declare(strict_types=1);

/**
 * MemberRoleCounts
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;

/**
 * MemberRoleCounts Class Doc Comment
 *
 * @description ロール別のメンバー数集計（フィルタ適用前の総件数）。 &#x60;include_counts&#x3D;true&#x60; の場合のみレスポンスに含まれます。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class MemberRoleCounts implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static string $openAPIModelName = 'MemberRoleCounts';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var array<string, string>
     */
    protected static array $openAPITypes = [
        'owner' => 'int',
        'admin' => 'int',
        'securityAdmin' => 'int',
        'member' => 'int'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var array<string, string|null>
     */
    protected static array $openAPIFormats = [
        'owner' => null,
        'admin' => null,
        'securityAdmin' => null,
        'member' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var array<string, bool>
     */
    protected static array $openAPINullables = [
        'owner' => false,
        'admin' => false,
        'securityAdmin' => false,
        'member' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var array<string, bool>
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * {@inheritdoc}
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * {@inheritdoc}
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * {@inheritdoc}
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * {@inheritdoc}
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'owner' => 'owner',
        'admin' => 'admin',
        'securityAdmin' => 'security_admin',
        'member' => 'member'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'owner' => 'setOwner',
        'admin' => 'setAdmin',
        'securityAdmin' => 'setSecurityAdmin',
        'member' => 'setMember'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'owner' => 'getOwner',
        'admin' => 'getAdmin',
        'securityAdmin' => 'getSecurityAdmin',
        'member' => 'getMember'
    ];

    /**
     * {@inheritdoc}
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * {@inheritdoc}
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * {@inheritdoc}
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * {@inheritdoc}
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('owner', $data ?? [], null);
        $this->setIfExists('admin', $data ?? [], null);
        $this->setIfExists('securityAdmin', $data ?? [], null);
        $this->setIfExists('member', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * {@inheritdoc}
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['owner'] === null) {
            $invalidProperties[] = "'owner' can't be null";
        }
        if (($this->container['owner'] < 0)) {
            $invalidProperties[] = "invalid value for 'owner', must be bigger than or equal to 0.";
        }

        if ($this->container['admin'] === null) {
            $invalidProperties[] = "'admin' can't be null";
        }
        if (($this->container['admin'] < 0)) {
            $invalidProperties[] = "invalid value for 'admin', must be bigger than or equal to 0.";
        }

        if ($this->container['securityAdmin'] === null) {
            $invalidProperties[] = "'securityAdmin' can't be null";
        }
        if (($this->container['securityAdmin'] < 0)) {
            $invalidProperties[] = "invalid value for 'securityAdmin', must be bigger than or equal to 0.";
        }

        if ($this->container['member'] === null) {
            $invalidProperties[] = "'member' can't be null";
        }
        if (($this->container['member'] < 0)) {
            $invalidProperties[] = "invalid value for 'member', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * {@inheritdoc}
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets owner
     *
     * @return int
     */
    public function getOwner(): int
    {
        return $this->container['owner'];
    }

    /**
     * Sets owner
     *
     * @param int $owner Owner ロールのメンバー数。
     *
     * @return $this
     */
    public function setOwner(int $owner): static
    {
        if (is_null($owner)) {
            throw new InvalidArgumentException('non-nullable owner cannot be null');
        }

        if (($owner < 0)) {
            throw new InvalidArgumentException('invalid value for $owner when calling MemberRoleCounts., must be bigger than or equal to 0.');
        }

        $this->container['owner'] = $owner;

        return $this;
    }

    /**
     * Gets admin
     *
     * @return int
     */
    public function getAdmin(): int
    {
        return $this->container['admin'];
    }

    /**
     * Sets admin
     *
     * @param int $admin Admin ロールのメンバー数。
     *
     * @return $this
     */
    public function setAdmin(int $admin): static
    {
        if (is_null($admin)) {
            throw new InvalidArgumentException('non-nullable admin cannot be null');
        }

        if (($admin < 0)) {
            throw new InvalidArgumentException('invalid value for $admin when calling MemberRoleCounts., must be bigger than or equal to 0.');
        }

        $this->container['admin'] = $admin;

        return $this;
    }

    /**
     * Gets securityAdmin
     *
     * @return int
     */
    public function getSecurityAdmin(): int
    {
        return $this->container['securityAdmin'];
    }

    /**
     * Sets securityAdmin
     *
     * @param int $securityAdmin Security Admin ロールのメンバー数。
     *
     * @return $this
     */
    public function setSecurityAdmin(int $securityAdmin): static
    {
        if (is_null($securityAdmin)) {
            throw new InvalidArgumentException('non-nullable securityAdmin cannot be null');
        }

        if (($securityAdmin < 0)) {
            throw new InvalidArgumentException('invalid value for $securityAdmin when calling MemberRoleCounts., must be bigger than or equal to 0.');
        }

        $this->container['securityAdmin'] = $securityAdmin;

        return $this;
    }

    /**
     * Gets member
     *
     * @return int
     */
    public function getMember(): int
    {
        return $this->container['member'];
    }

    /**
     * Sets member
     *
     * @param int $member 一般 Member ロールのメンバー数。
     *
     * @return $this
     */
    public function setMember(int $member): static
    {
        if (is_null($member)) {
            throw new InvalidArgumentException('non-nullable member cannot be null');
        }

        if (($member < 0)) {
            throw new InvalidArgumentException('invalid value for $member when calling MemberRoleCounts., must be bigger than or equal to 0.');
        }

        $this->container['member'] = $member;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


