<?php
declare(strict_types=1);

/**
 * OidcAuthorizeErrorCode
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * OidcAuthorizeErrorCode Class Doc Comment
 *
 * @description &#x60;/oauth/authorize&#x60; が 302 リダイレクトの &#x60;?error&#x3D;&#x60; クエリパラメータに設定するエラーコード (OIDC Core 1.0 Section 3.1.2.6)。  本実装が redirect 経由で返すのは &#x60;login_required&#x60; のみです。 RFC 6749 Section 4.1.2.1 が定義する他のエラー (&#x60;invalid_request&#x60; / &#x60;unsupported_response_type&#x60; など) は本実装では 422 Problem Details として &#x60;application/problem+json&#x60; 形式で返され、&#x60;OauthAuthorizeErrorCode&#x60; を参照してください。  - &#x60;login_required&#x60;: &#x60;prompt&#x3D;none&#x60; が指定されたが、認証済みセッションがないためユーザーインタラクションが必要 (OIDC Core Section 3.1.2.6)
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum OidcAuthorizeErrorCode: string
{
    case LOGIN_REQUIRED = 'login_required';
}


