<?php
declare(strict_types=1);

/**
 * OidcAuthorizeErrorCode
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.5.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * OidcAuthorizeErrorCode Class Doc Comment
 *
 * @description &#x60;/oauth/authorize&#x60; が 302 リダイレクトの &#x60;?error&#x3D;&#x60; クエリパラメータに設定するエラーコード (OIDC Core 1.0 Section 3.1.2.6)。  RFC 6749 Section 4.1.2.1 が定義する他のエラー (&#x60;invalid_request&#x60; / &#x60;unsupported_response_type&#x60; など) は本実装では 422 Problem Details として &#x60;application/problem+json&#x60; 形式で返され、&#x60;OauthAuthorizeErrorCode&#x60; を参照してください。  どちらも &#x60;prompt&#x3D;none&#x60; が指定されたときにのみ返されます。&#x60;prompt&#x3D;none&#x60; でなければ、 対話が必要な状況では認可サーバがそのための画面を表示します。  - &#x60;login_required&#x60;: 対話的な**認証**が必要だが &#x60;prompt&#x3D;none&#x60; のため実行できない   (OIDC Core Section 3.1.2.6)。セッションが無い場合と、SSO 強制 organization に対して   非 SSO セッションを再利用しようとした場合に返します - &#x60;interaction_required&#x60;: ユーザーは認証済みだが、続行するには対話が必要   (OIDC Core Section 3.1.2.6)。active な organization に 2 件以上所属していて   &#x60;organization_id&#x60; の指定が無く、どの organization にトークンをバインドするか   確定できない場合に返します。&#x60;prompt&#x3D;none&#x60; でなければ、この状況では認可サーバが   organization の選択画面を表示するため、クライアント側に選択 UI の実装は不要です。   &#x60;invitation_token&#x60; を指定した場合も、再利用可能なセッションがあれば返します。   招待の受諾は IdP 側でしか行えず、&#x60;prompt&#x3D;none&#x60; では IdP へリダイレクトできないためです   (セッションが無い場合や SSO 再認証が必要な場合は &#x60;login_required&#x60; が優先されます)
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum OidcAuthorizeErrorCode: string
{
    case LOGIN_REQUIRED = 'login_required';

    case INTERACTION_REQUIRED = 'interaction_required';
}


