<?php
declare(strict_types=1);

/**
 * OrganizationMemberSortBy
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.6.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * OrganizationMemberSortBy Class Doc Comment
 *
 * @description 組織メンバー一覧のソート基準フィールド。 - &#x60;name&#x60;: ユーザー表示名 - &#x60;email&#x60;: ユーザーメールアドレス - &#x60;role&#x60;: 組織内ロール - &#x60;joined_at&#x60;: 組織への参加日時 - &#x60;last_access&#x60;: 組織への最終アクセス日時
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum OrganizationMemberSortBy: string
{
    case NAME = 'name';

    case EMAIL = 'email';

    case ROLE = 'role';

    case JOINED_AT = 'joined_at';

    case LAST_ACCESS = 'last_access';
}


