<?php
declare(strict_types=1);

/**
 * PaginationMeta
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * PaginationMeta Class Doc Comment
 *
 * @description ページネーション情報。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class PaginationMeta implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'PaginationMeta';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'currentPage' => 'int',
        'perPage' => 'int',
        'total' => 'int',
        'lastPage' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'currentPage' => null,
        'perPage' => null,
        'total' => null,
        'lastPage' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'currentPage' => false,
        'perPage' => false,
        'total' => false,
        'lastPage' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'currentPage' => 'current_page',
        'perPage' => 'per_page',
        'total' => 'total',
        'lastPage' => 'last_page'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'currentPage' => 'setCurrentPage',
        'perPage' => 'setPerPage',
        'total' => 'setTotal',
        'lastPage' => 'setLastPage'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'currentPage' => 'getCurrentPage',
        'perPage' => 'getPerPage',
        'total' => 'getTotal',
        'lastPage' => 'getLastPage'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('currentPage', $data ?? [], null);
        $this->setIfExists('perPage', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('lastPage', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['currentPage'] === null) {
            $invalidProperties[] = "'currentPage' can't be null";
        }
        if (($this->container['currentPage'] < 1)) {
            $invalidProperties[] = "invalid value for 'currentPage', must be bigger than or equal to 1.";
        }

        if ($this->container['perPage'] === null) {
            $invalidProperties[] = "'perPage' can't be null";
        }
        if (($this->container['perPage'] > 100)) {
            $invalidProperties[] = "invalid value for 'perPage', must be smaller than or equal to 100.";
        }

        if (($this->container['perPage'] < 1)) {
            $invalidProperties[] = "invalid value for 'perPage', must be bigger than or equal to 1.";
        }

        if ($this->container['total'] === null) {
            $invalidProperties[] = "'total' can't be null";
        }
        if (($this->container['total'] < 0)) {
            $invalidProperties[] = "invalid value for 'total', must be bigger than or equal to 0.";
        }

        if ($this->container['lastPage'] === null) {
            $invalidProperties[] = "'lastPage' can't be null";
        }
        if (($this->container['lastPage'] < 1)) {
            $invalidProperties[] = "invalid value for 'lastPage', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets currentPage
     *
     * @return int
     */
    public function getCurrentPage(): int
    {
        return $this->container['currentPage'];
    }

    /**
     * Sets currentPage
     *
     * @param int $currentPage 現在のページ番号（1始まり）。
     *
     * @return $this
     */
    public function setCurrentPage(int $currentPage): static
    {
        if (is_null($currentPage)) {
            throw new InvalidArgumentException('non-nullable currentPage cannot be null');
        }

        if (($currentPage < 1)) {
            throw new InvalidArgumentException('invalid value for $currentPage when calling PaginationMeta., must be bigger than or equal to 1.');
        }

        $this->container['currentPage'] = $currentPage;

        return $this;
    }

    /**
     * Gets perPage
     *
     * @return int
     */
    public function getPerPage(): int
    {
        return $this->container['perPage'];
    }

    /**
     * Sets perPage
     *
     * @param int $perPage 1ページあたりの件数。
     *
     * @return $this
     */
    public function setPerPage(int $perPage): static
    {
        if (is_null($perPage)) {
            throw new InvalidArgumentException('non-nullable perPage cannot be null');
        }

        if (($perPage > 100)) {
            throw new InvalidArgumentException('invalid value for $perPage when calling PaginationMeta., must be smaller than or equal to 100.');
        }
        if (($perPage < 1)) {
            throw new InvalidArgumentException('invalid value for $perPage when calling PaginationMeta., must be bigger than or equal to 1.');
        }

        $this->container['perPage'] = $perPage;

        return $this;
    }

    /**
     * Gets total
     *
     * @return int
     */
    public function getTotal(): int
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int $total 総件数。
     *
     * @return $this
     */
    public function setTotal(int $total): static
    {
        if (is_null($total)) {
            throw new InvalidArgumentException('non-nullable total cannot be null');
        }

        if (($total < 0)) {
            throw new InvalidArgumentException('invalid value for $total when calling PaginationMeta., must be bigger than or equal to 0.');
        }

        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets lastPage
     *
     * @return int
     */
    public function getLastPage(): int
    {
        return $this->container['lastPage'];
    }

    /**
     * Sets lastPage
     *
     * @param int $lastPage 最終ページ番号。
     *
     * @return $this
     */
    public function setLastPage(int $lastPage): static
    {
        if (is_null($lastPage)) {
            throw new InvalidArgumentException('non-nullable lastPage cannot be null');
        }

        if (($lastPage < 1)) {
            throw new InvalidArgumentException('invalid value for $lastPage when calling PaginationMeta., must be bigger than or equal to 1.');
        }

        $this->container['lastPage'] = $lastPage;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


