<?php
declare(strict_types=1);

/**
 * ProblemDetails
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.5.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * ProblemDetails Class Doc Comment
 *
 * @description RFC 9457 Problem Details for HTTP APIs を表現する共通レスポンススキーマ。  RFC 上はすべてのメンバーが任意ですが、本サービスはコアメンバー (&#x60;type&#x60; / &#x60;title&#x60; / &#x60;status&#x60; / &#x60;detail&#x60; / &#x60;instance&#x60;) と共通の拡張メンバー (&#x60;trace_id&#x60; / &#x60;correlation_id&#x60; / &#x60;service_tag&#x60; / &#x60;occurred_at&#x60; / &#x60;log_reference&#x60;) を **常に** 返却するため、いずれも &#x60;required&#x60; として宣言しています。 &#x60;correlation_id&#x60; と &#x60;log_reference&#x60; は値が &#x60;null&#x60; になることはありますが、キーは常に存在します。  &#x60;errors&#x60; / &#x60;invalid_params&#x60; はバリデーション失敗時のみ付与されるため任意です。 エンドポイント固有の拡張メンバー（&#x60;organization_id&#x60; など）は &#x60;additionalProperties: true&#x60; により追加で返却されることがあります。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class ProblemDetails implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'ProblemDetails';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'type' => 'string',
        'title' => 'string',
        'status' => 'int',
        'detail' => 'string',
        'instance' => 'string',
        'traceId' => 'string',
        'correlationId' => 'string',
        'serviceTag' => 'string',
        'occurredAt' => '\DateTime',
        'logReference' => 'string',
        'errors' => 'array<string,string[]>',
        'invalidParams' => '\Studio\Auth\Model\InvalidParam[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'type' => 'uri-reference',
        'title' => null,
        'status' => 'int32',
        'detail' => null,
        'instance' => 'uri-reference',
        'traceId' => null,
        'correlationId' => null,
        'serviceTag' => null,
        'occurredAt' => 'date-time',
        'logReference' => null,
        'errors' => null,
        'invalidParams' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'type' => false,
        'title' => false,
        'status' => false,
        'detail' => false,
        'instance' => false,
        'traceId' => false,
        'correlationId' => true,
        'serviceTag' => false,
        'occurredAt' => false,
        'logReference' => true,
        'errors' => false,
        'invalidParams' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'type' => 'type',
        'title' => 'title',
        'status' => 'status',
        'detail' => 'detail',
        'instance' => 'instance',
        'traceId' => 'trace_id',
        'correlationId' => 'correlation_id',
        'serviceTag' => 'service_tag',
        'occurredAt' => 'occurred_at',
        'logReference' => 'log_reference',
        'errors' => 'errors',
        'invalidParams' => 'invalid_params'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'type' => 'setType',
        'title' => 'setTitle',
        'status' => 'setStatus',
        'detail' => 'setDetail',
        'instance' => 'setInstance',
        'traceId' => 'setTraceId',
        'correlationId' => 'setCorrelationId',
        'serviceTag' => 'setServiceTag',
        'occurredAt' => 'setOccurredAt',
        'logReference' => 'setLogReference',
        'errors' => 'setErrors',
        'invalidParams' => 'setInvalidParams'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'type' => 'getType',
        'title' => 'getTitle',
        'status' => 'getStatus',
        'detail' => 'getDetail',
        'instance' => 'getInstance',
        'traceId' => 'getTraceId',
        'correlationId' => 'getCorrelationId',
        'serviceTag' => 'getServiceTag',
        'occurredAt' => 'getOccurredAt',
        'logReference' => 'getLogReference',
        'errors' => 'getErrors',
        'invalidParams' => 'getInvalidParams'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('type', $data ?? [], 'about:blank');
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('detail', $data ?? [], null);
        $this->setIfExists('instance', $data ?? [], null);
        $this->setIfExists('traceId', $data ?? [], null);
        $this->setIfExists('correlationId', $data ?? [], null);
        $this->setIfExists('serviceTag', $data ?? [], null);
        $this->setIfExists('occurredAt', $data ?? [], null);
        $this->setIfExists('logReference', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
        $this->setIfExists('invalidParams', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if (($this->container['status'] > 599)) {
            $invalidProperties[] = "invalid value for 'status', must be smaller than or equal to 599.";
        }

        if (($this->container['status'] < 100)) {
            $invalidProperties[] = "invalid value for 'status', must be bigger than or equal to 100.";
        }

        if ($this->container['detail'] === null) {
            $invalidProperties[] = "'detail' can't be null";
        }
        if ($this->container['instance'] === null) {
            $invalidProperties[] = "'instance' can't be null";
        }
        if ($this->container['traceId'] === null) {
            $invalidProperties[] = "'traceId' can't be null";
        }
        if (!preg_match("/^[0-9a-f]{32}$/", $this->container['traceId'])) {
            $invalidProperties[] = "invalid value for 'traceId', must be conform to the pattern /^[0-9a-f]{32}$/.";
        }

        if ($this->container['correlationId'] === null && !$this->isNullableSetToNull('correlationId')) {
            $invalidProperties[] = "'correlationId' is required";
        }
        if ($this->container['serviceTag'] === null) {
            $invalidProperties[] = "'serviceTag' can't be null";
        }
        if ($this->container['occurredAt'] === null) {
            $invalidProperties[] = "'occurredAt' can't be null";
        }
        if ($this->container['logReference'] === null && !$this->isNullableSetToNull('logReference')) {
            $invalidProperties[] = "'logReference' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets type
     *
     * @return string
     */
    public function getType(): string
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type 問題タイプを識別する URI 参照 (RFC 3986)。 この URI は問題タイプを識別するもので、人間が読める説明へのリンクであることが推奨されます。
     *
     * @return $this
     */
    public function setType(string $type): static
    {
        if (is_null($type)) {
            throw new InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle(): string
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title 問題タイプの短い、人間が読める要約。 ローカライズを除き、同じ問題タイプでは常に同じ値であるべきです。
     *
     * @return $this
     */
    public function setTitle(string $title): static
    {
        if (is_null($title)) {
            throw new InvalidArgumentException('non-nullable title cannot be null');
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets status
     *
     * @return int
     */
    public function getStatus(): int
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param int $status この問題の HTTP ステータスコード。 情報提供的な性質を持ち、実際の HTTP レスポンスのステータスコードと一致する必要があります。
     *
     * @return $this
     */
    public function setStatus(int $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }

        if (($status > 599)) {
            throw new InvalidArgumentException('invalid value for $status when calling ProblemDetails., must be smaller than or equal to 599.');
        }
        if (($status < 100)) {
            throw new InvalidArgumentException('invalid value for $status when calling ProblemDetails., must be bigger than or equal to 100.');
        }

        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets detail
     *
     * @return string
     */
    public function getDetail(): string
    {
        return $this->container['detail'];
    }

    /**
     * Sets detail
     *
     * @param string $detail この問題の特定の発生に関する、人間が読める説明。 問題の詳細を提供し、クライアントが問題を理解・解決するのを助けることに焦点を当てます。
     *
     * @return $this
     */
    public function setDetail(string $detail): static
    {
        if (is_null($detail)) {
            throw new InvalidArgumentException('non-nullable detail cannot be null');
        }
        $this->container['detail'] = $detail;

        return $this;
    }

    /**
     * Gets instance
     *
     * @return string
     */
    public function getInstance(): string
    {
        return $this->container['instance'];
    }

    /**
     * Sets instance
     *
     * @param string $instance この問題の特定の発生を識別する URI 参照。 本サービスは `urn:trace:<trace_id>` 形式で返却します。
     *
     * @return $this
     */
    public function setInstance(string $instance): static
    {
        if (is_null($instance)) {
            throw new InvalidArgumentException('non-nullable instance cannot be null');
        }
        $this->container['instance'] = $instance;

        return $this;
    }

    /**
     * Gets traceId
     *
     * @return string
     */
    public function getTraceId(): string
    {
        return $this->container['traceId'];
    }

    /**
     * Sets traceId
     *
     * @param string $traceId W3C Trace Context に準拠した OpenTelemetry の trace ID（32 桁の小文字 16 進数）。 サポートへの問い合わせ時にこの値を伝えると、該当リクエストのトレースを特定できます。
     *
     * @return $this
     */
    public function setTraceId(string $traceId): static
    {
        if (is_null($traceId)) {
            throw new InvalidArgumentException('non-nullable traceId cannot be null');
        }

        if ((!preg_match("/^[0-9a-f]{32}$/", ObjectSerializer::toString($traceId)))) {
            throw new InvalidArgumentException("invalid value for \$traceId when calling ProblemDetails., must conform to the pattern /^[0-9a-f]{32}$/.");
        }

        $this->container['traceId'] = $traceId;

        return $this;
    }

    /**
     * Gets correlationId
     *
     * @return string|null
     */
    public function getCorrelationId(): ?string
    {
        return $this->container['correlationId'];
    }

    /**
     * Sets correlationId
     *
     * @param string|null $correlationId クライアントがリクエストヘッダーで指定した相関 ID。 指定がなかった場合は `null` になります（キー自体は常に存在します）。
     *
     * @return $this
     */
    public function setCorrelationId(?string $correlationId): static
    {
        if (is_null($correlationId)) {
            array_push($this->openAPINullablesSetToNull, 'correlationId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('correlationId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['correlationId'] = $correlationId;

        return $this;
    }

    /**
     * Gets serviceTag
     *
     * @return string
     */
    public function getServiceTag(): string
    {
        return $this->container['serviceTag'];
    }

    /**
     * Sets serviceTag
     *
     * @param string $serviceTag エラーが発生したサービス／エンドポイントの識別子。
     *
     * @return $this
     */
    public function setServiceTag(string $serviceTag): static
    {
        if (is_null($serviceTag)) {
            throw new InvalidArgumentException('non-nullable serviceTag cannot be null');
        }
        $this->container['serviceTag'] = $serviceTag;

        return $this;
    }

    /**
     * Gets occurredAt
     *
     * @return \DateTime
     */
    public function getOccurredAt(): \DateTime
    {
        return $this->container['occurredAt'];
    }

    /**
     * Sets occurredAt
     *
     * @param \DateTime $occurredAt エラーが発生した時刻 (RFC 3339 / ISO 8601)。
     *
     * @return $this
     */
    public function setOccurredAt(\DateTime $occurredAt): static
    {
        if (is_null($occurredAt)) {
            throw new InvalidArgumentException('non-nullable occurredAt cannot be null');
        }
        $this->container['occurredAt'] = $occurredAt;

        return $this;
    }

    /**
     * Gets logReference
     *
     * @return string|null
     */
    public function getLogReference(): ?string
    {
        return $this->container['logReference'];
    }

    /**
     * Sets logReference
     *
     * @param string|null $logReference ログ検索用の参照 ID。付与されない場合は `null` になります（キー自体は常に存在します）。
     *
     * @return $this
     */
    public function setLogReference(?string $logReference): static
    {
        if (is_null($logReference)) {
            array_push($this->openAPINullablesSetToNull, 'logReference');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('logReference', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['logReference'] = $logReference;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return array<string,string[]>|null
     */
    public function getErrors(): ?array
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param array<string,string[]>|null $errors バリデーション失敗時のみ付与される、フィールド名をキーとしたエラーメッセージ配列のマップ。 機械可読な用途には `invalid_params` を使用してください。
     *
     * @return $this
     */
    public function setErrors(?array $errors): static
    {
        if (is_null($errors)) {
            throw new InvalidArgumentException('non-nullable errors cannot be null');
        }
        $this->container['errors'] = $errors;

        return $this;
    }

    /**
     * Gets invalidParams
     *
     * @return \Studio\Auth\Model\InvalidParam[]|null
     */
    public function getInvalidParams(): ?array
    {
        return $this->container['invalidParams'];
    }

    /**
     * Sets invalidParams
     *
     * @param \Studio\Auth\Model\InvalidParam[]|null $invalidParams バリデーション失敗時のみ付与される、失敗したパラメータの一覧。
     *
     * @return $this
     */
    public function setInvalidParams(?array $invalidParams): static
    {
        if (is_null($invalidParams)) {
            throw new InvalidArgumentException('non-nullable invalidParams cannot be null');
        }
        $this->container['invalidParams'] = $invalidParams;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


