<?php
declare(strict_types=1);

/**
 * ResponseType
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * ResponseType Class Doc Comment
 *
 * @description OAuth 2.0 認可リクエストのレスポンスタイプ (RFC 6749 Section 3.1.1)。本実装は Authorization Code フロー のみをサポートします。  - &#x60;code&#x60;: Authorization Code フロー。認可サーバーは &#x60;redirect_uri&#x60; に認可コードを付与してリダイレクトします。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum ResponseType: string
{
    case CODE = 'code';
}


