<?php
declare(strict_types=1);

/**
 * RevokeErrorCode
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * RevokeErrorCode Class Doc Comment
 *
 * @description RFC 7009 Section 2.2.1 および RFC 6749 Section 5.2 で定義される &#x60;/oauth/revoke&#x60; エンドポイントのエラーコード。  - &#x60;invalid_request&#x60;: リクエストに必須パラメータが不足、無効なパラメータ値、重複パラメータ、または不正な形式 - &#x60;invalid_client&#x60;: クライアント認証失敗（未知のクライアント、認証情報なし、サポートされていない認証方式） - &#x60;unsupported_token_type&#x60;: 認可サーバーが提示されたトークンタイプの無効化をサポートしていない
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum RevokeErrorCode: string
{
    case INVALID_REQUEST = 'invalid_request';

    case INVALID_CLIENT = 'invalid_client';

    case UNSUPPORTED_TOKEN_TYPE = 'unsupported_token_type';
}


