<?php
declare(strict_types=1);

/**
 * TokenResponse
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.1.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

use ArrayAccess;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Studio\Auth\ObjectSerializer;
use JsonSerializable;

/**
 * TokenResponse Class Doc Comment
 *
 * @description RFC 6749 OAuth 2.0 Token Response に準拠したトークン発行レスポンス。  アクセストークンを必ず含み、条件に応じてリフレッシュトークンおよび OpenID Connect の ID トークンを含みます。
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class TokenResponse implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'TokenResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'accessToken' => 'string',
        'tokenType' => 'string',
        'expiresIn' => 'int',
        'refreshToken' => 'string',
        'idToken' => 'string',
        'scope' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'accessToken' => null,
        'tokenType' => null,
        'expiresIn' => null,
        'refreshToken' => null,
        'idToken' => null,
        'scope' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'accessToken' => false,
        'tokenType' => false,
        'expiresIn' => false,
        'refreshToken' => false,
        'idToken' => false,
        'scope' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'accessToken' => 'access_token',
        'tokenType' => 'token_type',
        'expiresIn' => 'expires_in',
        'refreshToken' => 'refresh_token',
        'idToken' => 'id_token',
        'scope' => 'scope'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'accessToken' => 'setAccessToken',
        'tokenType' => 'setTokenType',
        'expiresIn' => 'setExpiresIn',
        'refreshToken' => 'setRefreshToken',
        'idToken' => 'setIdToken',
        'scope' => 'setScope'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'accessToken' => 'getAccessToken',
        'tokenType' => 'getTokenType',
        'expiresIn' => 'getExpiresIn',
        'refreshToken' => 'getRefreshToken',
        'idToken' => 'getIdToken',
        'scope' => 'getScope'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }

    public const DISCRIMINATOR_MAP = [];
    public const TOKEN_TYPE_BEARER = 'Bearer';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public static function getTokenTypeAllowableValues()
    {
        return [
            self::TOKEN_TYPE_BEARER,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('accessToken', $data ?? [], null);
        $this->setIfExists('tokenType', $data ?? [], null);
        $this->setIfExists('expiresIn', $data ?? [], null);
        $this->setIfExists('refreshToken', $data ?? [], null);
        $this->setIfExists('idToken', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        if ($this->container['accessToken'] === null) {
            $invalidProperties[] = "'accessToken' can't be null";
        }
        if ((mb_strlen($this->container['accessToken']) < 1)) {
            $invalidProperties[] = "invalid value for 'accessToken', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['tokenType'] === null) {
            $invalidProperties[] = "'tokenType' can't be null";
        }
        $allowedValues = self::getTokenTypeAllowableValues();
        if (!is_null($this->container['tokenType']) && !in_array($this->container['tokenType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tokenType', must be one of '%s'",
                $this->container['tokenType'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['expiresIn'] === null) {
            $invalidProperties[] = "'expiresIn' can't be null";
        }
        if (($this->container['expiresIn'] < 1)) {
            $invalidProperties[] = "invalid value for 'expiresIn', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['refreshToken']) && (mb_strlen($this->container['refreshToken']) < 1)) {
            $invalidProperties[] = "invalid value for 'refreshToken', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['idToken']) && (mb_strlen($this->container['idToken']) < 1)) {
            $invalidProperties[] = "invalid value for 'idToken', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['scope']) && (mb_strlen($this->container['scope']) > 500)) {
            $invalidProperties[] = "invalid value for 'scope', the character length must be smaller than or equal to 500.";
        }

        if (!is_null($this->container['scope']) && !preg_match("/^(openid|email|profile|offline_access)( (openid|email|profile|offline_access))*$/", $this->container['scope'])) {
            $invalidProperties[] = "invalid value for 'scope', must be conform to the pattern /^(openid|email|profile|offline_access)( (openid|email|profile|offline_access))*$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accessToken
     *
     * @return string
     */
    public function getAccessToken(): string
    {
        return $this->container['accessToken'];
    }

    /**
     * Sets accessToken
     *
     * @param string $accessToken Bearer トークン (JWT)。HTTP Authorization ヘッダーで `Bearer {token}` として利用します。
     *
     * @return $this
     */
    public function setAccessToken(string $accessToken): static
    {
        if (is_null($accessToken)) {
            throw new InvalidArgumentException('non-nullable accessToken cannot be null');
        }

        if ((mb_strlen($accessToken) < 1)) {
            throw new InvalidArgumentException('invalid length for $accessToken when calling TokenResponse., must be bigger than or equal to 1.');
        }

        $this->container['accessToken'] = $accessToken;

        return $this;
    }

    /**
     * Gets tokenType
     *
     * @return string
     */
    public function getTokenType(): string
    {
        return $this->container['tokenType'];
    }

    /**
     * Sets tokenType
     *
     * @param string $tokenType トークンタイプ。現在は `Bearer` のみをサポートします。
     *
     * @return $this
     */
    public function setTokenType(string $tokenType): static
    {
        if (is_null($tokenType)) {
            throw new InvalidArgumentException('non-nullable tokenType cannot be null');
        }
        $allowedValues = self::getTokenTypeAllowableValues();
        if (!in_array($tokenType, $allowedValues, true)) {
            throw new InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tokenType', must be one of '%s'",
                    $tokenType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tokenType'] = $tokenType;

        return $this;
    }

    /**
     * Gets expiresIn
     *
     * @return int
     */
    public function getExpiresIn(): int
    {
        return $this->container['expiresIn'];
    }

    /**
     * Sets expiresIn
     *
     * @param int $expiresIn アクセストークンの有効期限 (秒)。クライアントはこの値を参考にトークン更新をスケジュールします。
     *
     * @return $this
     */
    public function setExpiresIn(int $expiresIn): static
    {
        if (is_null($expiresIn)) {
            throw new InvalidArgumentException('non-nullable expiresIn cannot be null');
        }

        if (($expiresIn < 1)) {
            throw new InvalidArgumentException('invalid value for $expiresIn when calling TokenResponse., must be bigger than or equal to 1.');
        }

        $this->container['expiresIn'] = $expiresIn;

        return $this;
    }

    /**
     * Gets refreshToken
     *
     * @return string|null
     */
    public function getRefreshToken(): ?string
    {
        return $this->container['refreshToken'];
    }

    /**
     * Sets refreshToken
     *
     * @param string|null $refreshToken 長寿命トークン。アクセストークンの更新に使用します。セキュアストレージで保管し、漏洩時は即座に失効させてください。 認可リクエストに `offline_access` スコープを含む場合のみ返却されます。
     *
     * @return $this
     */
    public function setRefreshToken(?string $refreshToken): static
    {
        if (is_null($refreshToken)) {
            throw new InvalidArgumentException('non-nullable refreshToken cannot be null');
        }

        if ((mb_strlen($refreshToken) < 1)) {
            throw new InvalidArgumentException('invalid length for $refreshToken when calling TokenResponse., must be bigger than or equal to 1.');
        }

        $this->container['refreshToken'] = $refreshToken;

        return $this;
    }

    /**
     * Gets idToken
     *
     * @return string|null
     */
    public function getIdToken(): ?string
    {
        return $this->container['idToken'];
    }

    /**
     * Sets idToken
     *
     * @param string|null $idToken OpenID Connect ID Token (JWT)。ユーザー認証結果としてクレームセットを含みます。
     *
     * @return $this
     */
    public function setIdToken(?string $idToken): static
    {
        if (is_null($idToken)) {
            throw new InvalidArgumentException('non-nullable idToken cannot be null');
        }

        if ((mb_strlen($idToken) < 1)) {
            throw new InvalidArgumentException('invalid length for $idToken when calling TokenResponse., must be bigger than or equal to 1.');
        }

        $this->container['idToken'] = $idToken;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope(): ?string
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope 発行されたアクセストークンのスコープ。元の認可リクエストと異なる場合のみ返却されます。 値には RFC 6749 で定義される `scope-token`（空白・ダブルクオート・バックスラッシュを含まない表示可能 ASCII）のみを使用します。
     *
     * @return $this
     */
    public function setScope(?string $scope): static
    {
        if (is_null($scope)) {
            throw new InvalidArgumentException('non-nullable scope cannot be null');
        }
        if ((mb_strlen($scope) > 500)) {
            throw new InvalidArgumentException('invalid length for $scope when calling TokenResponse., must be smaller than or equal to 500.');
        }
        if ((!preg_match("/^(openid|email|profile|offline_access)( (openid|email|profile|offline_access))*$/", ObjectSerializer::toString($scope)))) {
            throw new InvalidArgumentException("invalid value for \$scope when calling TokenResponse., must conform to the pattern /^(openid|email|profile|offline_access)( (openid|email|profile|offline_access))*$/.");
        }

        $this->container['scope'] = $scope;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


