<?php
declare(strict_types=1);

/**
 * TokenEndpointAuthMethod
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.6.0
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * TokenEndpointAuthMethod Class Doc Comment
 *
 * @description トークンエンドポイントでのクライアント認証方式 (OIDC Core 1.0 Section 9)。  - &#x60;client_secret_basic&#x60;: HTTP Basic 認証 - &#x60;client_secret_post&#x60;: リクエストボディでの送信 - &#x60;private_key_jwt&#x60;: JWT による認証
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum TokenEndpointAuthMethod: string
{
    case CLIENT_SECRET_BASIC = 'client_secret_basic';

    case CLIENT_SECRET_POST = 'client_secret_post';

    case PRIVATE_KEY_JWT = 'private_key_jwt';
}


