<?php
declare(strict_types=1);

/**
 * TokenErrorCode
 *
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Model;

/**
 * TokenErrorCode Class Doc Comment
 *
 * @description RFC 6749 Section 5.2 で定義される OAuth 2.0 Token エンドポイントのエラーコード。  - &#x60;invalid_request&#x60;: リクエストに必須パラメータが不足、無効なパラメータ値、重複パラメータ、または不正な形式 - &#x60;invalid_client&#x60;: クライアント認証失敗（未知のクライアント、認証情報なし、サポートされていない認証方式） - &#x60;invalid_grant&#x60;: 認可コードまたはリフレッシュトークンが無効、期限切れ、失効、または &#x60;redirect_uri&#x60; 不一致 - &#x60;unauthorized_client&#x60;: 認証されたクライアントがこのグラントタイプを使用する権限がない - &#x60;unsupported_grant_type&#x60;: 認可サーバーがこのグラントタイプをサポートしていない - &#x60;invalid_scope&#x60;: 要求されたスコープが無効、未知、不正、または元の認可範囲を超過
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
enum TokenErrorCode: string
{
    case INVALID_REQUEST = 'invalid_request';

    case INVALID_CLIENT = 'invalid_client';

    case INVALID_GRANT = 'invalid_grant';

    case UNAUTHORIZED_CLIENT = 'unauthorized_client';

    case UNSUPPORTED_GRANT_TYPE = 'unsupported_grant_type';

    case INVALID_SCOPE = 'invalid_scope';
}


