<?php
declare(strict_types=1);

/**
 * APIApi
 * PHP version 8.1
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Auth Service API
 *
 * 認証サービスの API 仕様書
 *
 * The version of the OpenAPI document: 0.2.24
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.21.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Studio\Auth\Api;

use InvalidArgumentException;
use JsonException;
use Throwable;
use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use GuzzleHttp\Promise\PromiseInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Studio\Auth\ApiException;
use Studio\Auth\Configuration;
use Studio\Auth\HeaderSelector;
use Studio\Auth\FormDataProcessor;
use Studio\Auth\Model\ProblemDetails;
use Studio\Auth\ObjectSerializer;

/**
 * APIApi Class Doc Comment
 *
 * @package  Studio\Auth
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class APIApi
{
    /**
     * @var ClientInterface
     */
    protected ClientInterface $client;

    /**
     * @var Configuration
     */
    protected Configuration $config;

    /**
     * @var HeaderSelector
     */
    protected HeaderSelector $headerSelector;

    /**
     * @var int Host index
     */
    protected int $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'checkSsoEnforcement' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null   $config
     * @param HeaderSelector|null  $selector
     * @param int                  $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex(int $hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex(): int
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig(): Configuration
    {
        return $this->config;
    }

    /**
     * Operation checkSsoEnforcement
     *
     * SSO 強制判定エンドポイント
     *
     * @param  string|null $email 判定対象のメールアドレス (optional)
     * @param  string|null $sub 判定対象のユーザーID（UUID） (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkSsoEnforcement'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return \Studio\Auth\Model\CheckSsoEnforcementResponse
     */
    public function checkSsoEnforcement(
        ?string $email = null,
        ?string $sub = null,
        string $contentType = self::contentTypes['checkSsoEnforcement'][0]
    ): \Studio\Auth\Model\CheckSsoEnforcementResponse
    {
        [$response] = $this->checkSsoEnforcementWithHttpInfo($email, $sub, $contentType);

        return $response;
    }

    /**
     * Operation checkSsoEnforcementWithHttpInfo
     *
     * SSO 強制判定エンドポイント
     *
     * @param  string|null $email 判定対象のメールアドレス (optional)
     * @param  string|null $sub 判定対象のユーザーID（UUID） (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkSsoEnforcement'] to see the possible values for this operation
     *
     * @throws ApiException on non-2xx response or if the response body is not in the expected format
     * @throws InvalidArgumentException
     * @return array{0: \Studio\Auth\Model\CheckSsoEnforcementResponse, 1: int, 2: array<string, string[]>}
     */
    public function checkSsoEnforcementWithHttpInfo(
        ?string $email = null,
        ?string $sub = null,
        string $contentType = self::contentTypes['checkSsoEnforcement'][0]
    ): array
    {
        $request = $this->checkSsoEnforcementRequest($email, $sub, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null,
                    $e,
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null,
                    $e,
                );
            }

            $statusCode = $response->getStatusCode();

            // Non-2xx responses are thrown as ApiException by Guzzle (http_errors=true),
            // so execution reaches here only for 2xx. The guard below is a safety net for
            // edge cases such as 1xx/3xx responses that bypass Guzzle's RequestException.
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Unexpected non-2xx response status received from API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Studio\Auth\Model\CheckSsoEnforcementResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            // Attempt to decode the error body as a ProblemDetails document (RFC 9457).
            // Non-JSON bodies or schemas that don't match ProblemDetails leave $problem null,
            // which is the caller's signal that the upstream did not return a structured error.
            $problem = null;
            $body = $e->getResponseBody();
            if ($body !== null && $body !== '') {
                try {
                    $decoded = ObjectSerializer::deserialize(
                        $body,
                        ProblemDetails::class,
                        $e->getResponseHeaders()
                    );
                    if ($decoded instanceof ProblemDetails) {
                        $problem = $decoded;
                    }
                } catch (Throwable) {
                    // Best-effort: keep $problem null and let the caller inspect the raw body.
                }
            }

            throw ApiException::specialize($e, $problem);
        }
    }

    /**
     * Operation checkSsoEnforcementAsync
     *
     * SSO 強制判定エンドポイント
     *
     * @param  string|null $email 判定対象のメールアドレス (optional)
     * @param  string|null $sub 判定対象のユーザーID（UUID） (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkSsoEnforcement'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function checkSsoEnforcementAsync(
        ?string $email = null,
        ?string $sub = null,
        string $contentType = self::contentTypes['checkSsoEnforcement'][0]
    ): PromiseInterface
    {
        return $this->checkSsoEnforcementAsyncWithHttpInfo($email, $sub, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation checkSsoEnforcementAsyncWithHttpInfo
     *
     * SSO 強制判定エンドポイント
     *
     * @param  string|null $email 判定対象のメールアドレス (optional)
     * @param  string|null $sub 判定対象のユーザーID（UUID） (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkSsoEnforcement'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return PromiseInterface
     */
    public function checkSsoEnforcementAsyncWithHttpInfo(
        ?string $email = null,
        ?string $sub = null,
        string $contentType = self::contentTypes['checkSsoEnforcement'][0]
    ): PromiseInterface
    {
        $returnType = '\Studio\Auth\Model\CheckSsoEnforcementResponse';
        $request = $this->checkSsoEnforcementRequest($email, $sub, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if (in_array($returnType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    $body = (string) $response->getBody();
                    $headers = $response->getHeaders();

                    $base = new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $headers,
                        $body,
                        $exception,
                    );

                    $problem = null;
                    if ($body !== '') {
                        try {
                            $decoded = ObjectSerializer::deserialize(
                                $body,
                                ProblemDetails::class,
                                $headers
                            );
                            if ($decoded instanceof ProblemDetails) {
                                $problem = $decoded;
                            }
                        } catch (Throwable) {
                            // Best-effort: leave $problem null.
                        }
                    }

                    throw ApiException::specialize($base, $problem);
                }
            );
    }

    /**
     * Create request for operation 'checkSsoEnforcement'
     *
     * @param  string|null $email 判定対象のメールアドレス (optional)
     * @param  string|null $sub 判定対象のユーザーID（UUID） (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['checkSsoEnforcement'] to see the possible values for this operation
     *
     * @throws InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function checkSsoEnforcementRequest(
        ?string $email = null,
        ?string $sub = null,
        string $contentType = self::contentTypes['checkSsoEnforcement'][0]
    ): Request
    {




        $resourcePath = '/api/sso-enforcement/check';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $email,
            'email', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sub,
            'sub', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'application/problem+json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption(): array
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response,
    ): array {
        if (in_array($dataType, ['\SplFileObject', '\Psr\Http\Message\StreamInterface'])) {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content,
                        $exception,
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode,
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
